prtable: Add second table for open PRs.
minio/buggy pull request #3
Opened 2017-04-27 01:18 UTC by deekoder

2017-04-27 01:44 UTC, harshavardhana requested changes

2017-04-27 01:44 UTC, harshavardhana commented on getPRs.go
> +package main
Missing license header..

2017-04-27 02:03 UTC, deekoder commented on getPRs.go
> +package main
oh yes.

2017-04-27 02:10 UTC, deekoder commented on getPRs.go
> +package main
done.

2017-04-27 02:44 UTC, harshavardhana commented on getPRs.go
> +package main
actually this is not the header.. you can take an example from minio server project.

2017-04-27 02:44 UTC, harshavardhana commented on getPRs.go
> +package main
This is MIT header.

2017-04-27 15:52 UTC, deekoder commented on getPRs.go
> +package main
My bad. Done.

2017-04-27 21:12 UTC, harshavardhana requested changes

2017-04-27 21:12 UTC, harshavardhana commented on getPRs.go
> + * Below main package has canonical imports for 'go get' and 'go build'
You don't need this.. this is specific to minio server only.

2017-04-27 21:12 UTC, harshavardhana commented on getPRs.go
> + * Minio Cloud Storage, (C) 2016,2017 Minio, Inc.
Keep it `Buggy, (C) 2017 Minio, Inc.`

2017-04-28 18:11 UTC, deekoder commented on getPRs.go
> + * Minio Cloud Storage, (C) 2016,2017 Minio, Inc.
Done

2017-04-28 18:12 UTC, deekoder commented on getPRs.go
> + * Below main package has canonical imports for 'go get' and 'go build'
ugh missed this. Done.

2017-04-28 18:28 UTC, harshavardhana approved these changes

2017-04-28 19:15 UTC, merged