refactor: Refactor code to start using go-github library to get reviewers list.
minio/buggy pull request #37
Opened 2017-05-16 22:06 UTC by deekoder

2017-05-16 22:10 UTC, harshavardhana requested changes

2017-05-16 22:10 UTC, harshavardhana commented on github-get-reviewers.go
> +		fmt.Println("Unable to get Reviewers for %s", number)
You don't want to return right here?

2017-05-16 22:10 UTC, harshavardhana commented on github-get-reviewers.go
> +		fmt.Println("Unable to get Reviewers for %s", number)
BTW comments "//a" should be "// a"

2017-05-16 22:30 UTC, deekoder commented on github-get-reviewers.go
> +		fmt.Println("Unable to get Reviewers for %s", number)
yes @harshavardhana  i dont want to return. I will fix the space issue.

2017-05-16 22:37 UTC, deekoder commented on github-get-reviewers.go
> +		fmt.Println("Unable to get Reviewers for %s", number)
fixed

2017-05-17 00:33 UTC, harshavardhana commented on github-get-reviewers.go
> +	//State string `json:"state"`
One more comment missing.. the spacing.

2017-05-17 00:35 UTC, deekoder commented on github-get-reviewers.go
> +	//State string `json:"state"`
that is a json struct variable i will be using later. Anyway removed for now.

2017-05-17 00:39 UTC, harshavardhana approved these changes

2017-05-17 00:39 UTC, merged