Fixes the PR link issue
minio/buggy pull request #53
Opened 2017-06-28 17:48 UTC by ebozduman

Issue#49

2017-06-28 19:58 UTC, rushenn approved these changes
LGTM

2017-06-28 23:45 UTC, deekoder requested changes
Doesnt work. Am i missing any instructions?

2017-06-28 23:49 UTC, deekoder commented
```
functions.js:160 Uncaught TypeError: Cannot read property 'substr' of undefined
    at HTMLTableRowElement.<anonymous> (functions.js:160)
    at HTMLBodyElement.dispatch (jquery.min.js:3)
    at HTMLBodyElement.q.handle (jquery.min.js:3)
```

2017-06-29 00:32 UTC, deekoder approved these changes

2017-06-29 00:32 UTC, merged